### ISSUE TITLE
Error "TypeError: reporter is not a function"

### ISSUE THREAD

**Issue by muescha** [Hocdoc/vfile-reporter-position#1]
## Steps

- installed: `yarn global add remark-cli`
- installed: `yarn add vfile-reporter-position --dev -W` 
- installed: `yarn add vfile-reporter-json --dev -W` 

- run: `remark docs/ --report vfile-reporter-json` -> no error
- run: `remark docs/ --report vfile-reporter-position` -> error

## Stacktrace

```shell
$ remark docs/ --report vfile-reporter-position
TypeError: reporter is not a function
    at log (/Users/muescha/.config/yarn/global/node_modules/unified-engine/lib/file-set-pipeline/log.js:23:17)
    at wrapped (/Users/muescha/.config/yarn/global/node_modules/trough/wrap.js:25:19)
    at next (/Users/muescha/.config/yarn/global/node_modules/trough/index.js:57:24)
    at FileSet.done (/Users/muescha/.config/yarn/global/node_modules/trough/wrap.js:55:16)
    at FileSet.emit (events.js:210:5)
    at FileSet.one (/Users/muescha/.config/yarn/global/node_modules/unified-engine/lib/file-set.js:111:10)
    at FileSet.emit (events.js:210:5)
    at done (/Users/muescha/.config/yarn/global/node_modules/unified-engine/lib/file-set-pipeline/transform.js:54:15)
    at next (/Users/muescha/.config/yarn/global/node_modules/trough/index.js:59:14)
    at done (/Users/muescha/.config/yarn/global/node_modules/trough/wrap.js:55:16)
```
## Versions

```shell
$ remark --version
remark: 12.0.0, remark-cli: 8.0.0
$ node --version
v12.13.1
$ nvm --version
0.35.3
$ yarn --version
1.21.0
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.15.3
BuildVersion:   19D76
```

**Comment by Hocdoc** [comment]
Thanks for your detailed bug report. :-)

I use directly the API of vfile-reporter-position which works fine. I didn't test it together with `remark` or thought anybody would use it with `remark`. Other reporters might be more useful than this very specific reporter.

So I will look into this issue later if I have more free time or will gladly accept a PR resolving this issue.

**Comment by muescha** [comment]
i can monkey patch it with adding this lines:

```javascript
  if(reporter.reporter){
    reporter = reporter.reporter
  }
```

node_modules/unified-engine/lib/file-set-pipeline/log.js:23:17

https://github.com/unifiedjs/unified-engine/blob/5f503962d65376f2170f9c2241e1b1471a2a77bb/lib/file-set-pipeline/log.js#L22-L30

**Comment by muescha** [comment]
i see other reporter are using:

`module.exports = reporter`
